# Generated by Django 4.1.2 on 2024-12-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price_pool', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='img')),
                ('rulebook', models.FileField(upload_to='file')),
            ],
        ),
    ]
